### PR TITLE
Symlinks are transformed as well, which leads into broken symlinks.

### PR DESCRIPTION
**Pull request by waja**
Adding the correct transformation scope flags here.

https://www.gnu.org/software/tar/manual/html_section/tar_51.html
mentions a way to fix this:

```
In addition, several transformation scope flags are supported, that control to what files transformations apply. These are:

[...]

`S'
Do not apply transformation to symbolic link targets.
```

### CODE REVIEW

**Comment by waja** [comment]
You can compare https://github.com/waja/maldetect/runs/1370635825?check_suite_focus=true#step:5:1287 against https://github.com/waja/maldetect/runs/1371011875?check_suite_focus=true#step:5:1287, which has the fix in use.

**Comment by m-roberts** [comment]
I can see that this fixes your issue. However, I feel that the default behaviour is more desirable in the majority of use-cases (assuming that I've understood it correctly).

Perhaps this is something that can be added as an input? Willing to consider something if it's generic and sensible.

AFAIK, Debian packages do not support symlinks non-existent locations, so the tar command would be correct - to add this flag - if I understand correctly - would mean that other symlinks would not resolve properly either, right?

**Comment by waja** [comment]
> I can see that this fixes your issue. However, I feel that the default behaviour is more desirable in the majority of use-cases (assuming that I've understood it correctly).

I would say, it is in any case broken for symlinks, as you are running the transformation on directory level. See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775247.

**Comment by waja** [comment]
transformation is not needed at all. Opened #16.

**Pull request closed without merging**
